# Generated by Django 3.2.25 on 2026-04-30 17:20

import core.models.academico
import core.models.banners
import core.models.publicaciones.archivos
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('rol', models.CharField(choices=[('autor', 'Autor'), ('autor_externo', 'Autor externo')], default='autor', max_length=20)),
                ('microsoft_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('ms_graph_id', models.CharField(blank=True, max_length=150, null=True)),
                ('ms_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ms_given_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ms_surname', models.CharField(blank=True, max_length=255, null=True)),
                ('ms_mail', models.EmailField(blank=True, max_length=255, null=True)),
                ('ms_user_principal_name', models.EmailField(blank=True, max_length=255, null=True)),
                ('ms_job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('ms_department', models.CharField(blank=True, max_length=255, null=True)),
                ('ms_office_location', models.CharField(blank=True, max_length=255, null=True)),
                ('ms_business_phones', models.JSONField(blank=True, null=True)),
                ('ms_mobile_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('ms_raw_claims', models.JSONField(blank=True, null=True)),
                ('ms_raw_graph', models.JSONField(blank=True, null=True)),
                ('auth_source', models.CharField(choices=[('local', 'Local (BD)'), ('microsoft', 'Microsoft 365')], default='local', max_length=20)),
                ('perfil_completo', models.BooleanField(default=False)),
                ('creado_desde_selector', models.BooleanField(default=False)),
                ('perfil_banner_snooze_until', models.DateTimeField(blank=True, null=True)),
                ('ms_last_sync', models.DateTimeField(blank=True, null=True)),
                ('profile_edit_attempts_left', models.PositiveSmallIntegerField(default=3)),
                ('profile_edit_locked', models.BooleanField(default=False)),
                ('profile_edit_lock_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_edit_until', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='usuarios/avatar/')),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='AreaConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'areas_conocimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_articulo', models.CharField(choices=[('alto_impacto', 'Alto impacto'), ('regional', 'Regional')], max_length=20)),
                ('nombre_articulo', models.CharField(max_length=255)),
                ('base_datos_indexada', models.CharField(blank=True, choices=[('latindex', 'Latindex'), ('scielo', 'SciELO'), ('redalyc', 'Redalyc'), ('dialnet', 'Dialnet'), ('google_scholar', 'Google Scholar'), ('otra', 'Otra')], max_length=50, null=True)),
                ('base_datos_otra', models.CharField(blank=True, max_length=150, null=True)),
                ('codigo_doi', models.CharField(blank=True, max_length=150, null=True)),
                ('codigo_issn', models.CharField(max_length=100)),
                ('nombre_revista', models.CharField(max_length=255)),
                ('numero_revista', models.PositiveIntegerField(blank=True, null=True)),
                ('link_revista', models.URLField(blank=True, max_length=500, null=True)),
                ('link_publicacion', models.URLField(blank=True, max_length=500, null=True)),
                ('factor_impacto', models.CharField(blank=True, choices=[('sjr', 'SJR'), ('jcr', 'JCR')], max_length=20, null=True)),
                ('cuartil', models.CharField(blank=True, choices=[('q1', 'Q1'), ('q2', 'Q2'), ('q3', 'Q3'), ('q4', 'Q4'), ('sin_cuartil', 'Sin cuartil')], max_length=20, null=True)),
                ('sjr', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'articulos',
                'ordering': ['-publicacion__fecha_publicacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('es_externo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'autores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=220, verbose_name='Título del aviso')),
                ('eyebrow', models.CharField(blank=True, default='', max_length=60, verbose_name='Etiqueta superior')),
                ('text', models.TextField(blank=True, default='', verbose_name='Mensaje del aviso')),
                ('recent_label', models.CharField(blank=True, default='', max_length=60, verbose_name='Etiqueta de actualización')),
                ('image', models.ImageField(upload_to=core.models.banners.banner_upload_to, verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'banners',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BannerConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('eyebrow', models.CharField(default='SGPC ULEAM', max_length=60)),
                ('title', models.CharField(default='Novedades institucionales', max_length=220)),
                ('text', models.TextField(default='Se detectó una actualización en los avisos del sistema. Revise la información antes de continuar.')),
                ('recent_label', models.CharField(default='Actualización reciente', max_length=60)),
                ('stage_width', models.PositiveIntegerField(default=1260)),
                ('stage_height', models.PositiveIntegerField(default=640)),
                ('media_pane_width', models.PositiveIntegerField(default=806)),
                ('display_mode', models.CharField(choices=[('mixed', 'Banner + texto'), ('banner', 'Solo banner'), ('text', 'Solo texto')], default='mixed', max_length=16, verbose_name='Modo de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración global de banners',
                'verbose_name_plural': 'Configuración global de banners',
                'db_table': 'banner_configuracion',
                'ordering': ['singleton_key'],
            },
        ),
        migrations.CreateModel(
            name='CapituloLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_capitulo', models.CharField(max_length=255)),
                ('nombre_libro', models.CharField(max_length=255)),
                ('codigo_isbn', models.CharField(max_length=100)),
                ('editor_compilador', models.CharField(max_length=255)),
                ('revisor_par_arbitraje', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('link_capitulo', models.URLField()),
            ],
            options={
                'db_table': 'capitulos_libros',
                'ordering': ['nombre_capitulo'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('geoname_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('admin1', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('siglas', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facultades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libro', models.CharField(max_length=255)),
                ('codigo_isbn', models.CharField(max_length=100)),
                ('editorial_compilador', models.CharField(max_length=255)),
                ('revisor_par_arbitraje', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('link_libro', models.URLField()),
            ],
            options={
                'db_table': 'libros',
                'ordering': ['nombre_libro'],
            },
        ),
        migrations.CreateModel(
            name='MicrosoftMappingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_contains', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title_contains', models.CharField(blank=True, max_length=255, null=True)),
                ('office_location_contains', models.CharField(blank=True, max_length=255, null=True)),
                ('prioridad', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'microsoft_mapping_rules',
                'ordering': ['-prioridad', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('iso2', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('iso3', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('geoname_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'paises',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ponencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=255)),
                ('nombre_ponencia', models.CharField(max_length=255)),
                ('codigo_issn_isbn', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_presentacion', models.CharField(blank=True, choices=[('magistral', 'Conferencia magistral'), ('oral', 'Conferencia oral'), ('poster', 'Poster')], max_length=20, null=True)),
                ('link_evento', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ponencias',
                'ordering': ['nombre_ponencia'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('arrastre', 'Arrastre'), ('cierre', 'Cierre')], db_index=True, default='nuevo', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin_planificada', models.DateField(blank=True, null=True)),
                ('fecha_fin_prorrogada', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('anio_inicio', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('anio_fin', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to=core.models.academico.proyecto_pdf_upload_path)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proyectos',
                'ordering': ['-anio_inicio', 'nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('principal', 'Investigador principal'), ('coinvestigador', 'Coinvestigador'), ('colaborador', 'Colaborador')], default='principal', max_length=20)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'proyectos_autores',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrado_por_admin', models.BooleanField(default=False)),
                ('origen_tipo', models.CharField(choices=[('ninguno', 'Ninguno'), ('tic', 'Trabajo de integración curricular'), ('maestria', 'Tesis de maestría'), ('doctoral', 'Tesis doctoral')], default='ninguno', max_length=20)),
                ('origen_grado', models.CharField(blank=True, help_text='Especificar el grado cuando el origen lo requiera (p.ej., TIC).', max_length=120, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='publicaciones/pdf/')),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('anio_publicacion', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'publicaciones',
                'ordering': ['tipo', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='PublicacionArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('archivo', models.FileField(upload_to=core.models.publicaciones.archivos.publicacion_archivo_upload_path)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'publicaciones_archivos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PublicacionAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_autoria', models.CharField(choices=[('principal', 'Autor Principal'), ('coautor', 'Coautor')], max_length=20)),
                ('orden', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'publicaciones_autores',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Subarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'subareas_conocimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.SlugField(max_length=60, unique=True)),
                ('categoria', models.CharField(choices=[('ponencia', 'Ponencia'), ('articulo', 'Artículo'), ('libro', 'Libro'), ('capitulo', 'Capítulo')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'tipos_publicacion',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='tipopublicacion',
            index=models.Index(fields=['categoria'], name='tipos_publi_categor_524ed2_idx'),
        ),
        migrations.AddField(
            model_name='subarea',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='core.areaconocimiento'),
        ),
        migrations.AddField(
            model_name='publicacionautor',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='core.autor'),
        ),
        migrations.AddField(
            model_name='publicacionautor',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='core.publicacion'),
        ),
        migrations.AddField(
            model_name='publicacionarchivo',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='core.publicacion'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='admin_registrador',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_registradas_como_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.areaconocimiento'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='core.carrera'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciudad'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='core.facultad'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pais'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to='core.proyecto'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='subarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subarea'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='core.tipopublicacion'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='usuario_creador',
            field=models.ForeignKey(limit_choices_to={'rol': 'autor'}, on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyectoautor',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_participaciones', to='core.autor'),
        ),
        migrations.AddField(
            model_name='proyectoautor',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='core.proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='autores',
            field=models.ManyToManyField(blank=True, related_name='proyectos', through='core.ProyectoAutor', to='core.Autor'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='core.carrera'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creado_por',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='publicacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ponencia', to='core.publicacion'),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pais',
            index=models.Index(fields=['iso2'], name='paises_iso2_2f46ad_idx'),
        ),
        migrations.AddIndex(
            model_name='pais',
            index=models.Index(fields=['iso3'], name='paises_iso3_c2bca7_idx'),
        ),
        migrations.AddConstraint(
            model_name='pais',
            constraint=models.UniqueConstraint(condition=models.Q(('iso2__isnull', False)), fields=('iso2',), name='unique_pais_iso2'),
        ),
        migrations.AddConstraint(
            model_name='pais',
            constraint=models.UniqueConstraint(condition=models.Q(('iso3__isnull', False)), fields=('iso3',), name='unique_pais_iso3'),
        ),
        migrations.AddField(
            model_name='microsoftmappingrule',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.carrera'),
        ),
        migrations.AddField(
            model_name='microsoftmappingrule',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.facultad'),
        ),
        migrations.AddField(
            model_name='libro',
            name='publicacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='libro', to='core.publicacion'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='core.pais'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='core.facultad'),
        ),
        migrations.AddField(
            model_name='capitulolibro',
            name='publicacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capitulo_libro', to='core.publicacion'),
        ),
        migrations.AddField(
            model_name='autor',
            name='publicaciones',
            field=models.ManyToManyField(blank=True, related_name='autores', through='core.PublicacionAutor', to='core.Publicacion'),
        ),
        migrations.AddField(
            model_name='autor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articulo',
            name='publicacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='articulo', to='core.publicacion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.carrera'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.facultad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='subarea',
            index=models.Index(fields=['area', 'nombre'], name='subareas_co_area_id_a2e30f_idx'),
        ),
        migrations.AddConstraint(
            model_name='subarea',
            constraint=models.UniqueConstraint(fields=('nombre', 'area'), name='unique_subarea_por_area'),
        ),
        migrations.AddIndex(
            model_name='publicacionautor',
            index=models.Index(fields=['publicacion', 'rol_autoria'], name='publicacion_publica_a826e5_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacionautor',
            index=models.Index(fields=['autor'], name='publicacion_autor_i_692de0_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicacionautor',
            constraint=models.UniqueConstraint(fields=('publicacion', 'autor'), name='unique_autor_por_publicacion'),
        ),
        migrations.AddConstraint(
            model_name='publicacionautor',
            constraint=models.UniqueConstraint(fields=('publicacion', 'orden'), name='unique_orden_por_publicacion'),
        ),
        migrations.AddIndex(
            model_name='publicacionarchivo',
            index=models.Index(fields=['publicacion'], name='publicacion_publica_90d234_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['anio_publicacion'], name='publicacion_anio_pu_ef384d_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['carrera', 'anio_publicacion'], name='publicacion_carrera_9a3c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['facultad', 'anio_publicacion'], name='publicacion_faculta_9df43f_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['tipo', 'anio_publicacion'], name='publicacion_tipo_id_f7e111_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['origen_tipo', 'anio_publicacion'], name='publicacion_origen__96aaa5_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['usuario_creador'], name='publicacion_usuario_59c0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['registrado_por_admin'], name='publicacion_registr_11c26a_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['admin_registrador'], name='publicacion_admin_r_aaaf4c_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['usuario_creador', 'registrado_por_admin'], name='publicacion_usuario_a68cee_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicacion',
            constraint=models.UniqueConstraint(fields=('tipo', 'numero'), name='unique_numero_por_tipo'),
        ),
        migrations.AddIndex(
            model_name='proyectoautor',
            index=models.Index(fields=['proyecto', 'rol'], name='proyectos_a_proyect_7ed774_idx'),
        ),
        migrations.AddIndex(
            model_name='proyectoautor',
            index=models.Index(fields=['autor'], name='proyectos_a_autor_i_3ce2f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='proyectoautor',
            constraint=models.UniqueConstraint(fields=('proyecto', 'autor'), name='unique_autor_por_proyecto'),
        ),
        migrations.AddConstraint(
            model_name='proyectoautor',
            constraint=models.UniqueConstraint(fields=('proyecto', 'orden'), name='unique_orden_por_proyecto'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['estado'], name='proyectos_estado_338660_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['anio_inicio'], name='proyectos_anio_in_15e256_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['anio_fin'], name='proyectos_anio_fi_4ac8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['estado', 'anio_inicio'], name='proyectos_estado_2a24da_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['carrera'], name='proyectos_carrera_c83c81_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['creado_por'], name='proyectos_creado__b7444b_idx'),
        ),
        migrations.AddIndex(
            model_name='ponencia',
            index=models.Index(fields=['nombre_evento'], name='ponencias_nombre__7b3792_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'used_at'], name='password_re_user_id_9530b9_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['created_at'], name='password_re_created_265757_idx'),
        ),
        migrations.AddIndex(
            model_name='microsoftmappingrule',
            index=models.Index(fields=['activo'], name='microsoft_m_activo_566cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='microsoftmappingrule',
            index=models.Index(fields=['prioridad'], name='microsoft_m_priorid_fd1133_idx'),
        ),
        migrations.AddIndex(
            model_name='microsoftmappingrule',
            index=models.Index(fields=['activo', 'prioridad'], name='microsoft_m_activo_cb5f66_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['codigo_isbn'], name='libros_codigo__0fcf0b_idx'),
        ),
        migrations.AddIndex(
            model_name='ciudad',
            index=models.Index(fields=['pais', 'nombre'], name='ciudades_pais_id_0cdaac_idx'),
        ),
        migrations.AddIndex(
            model_name='ciudad',
            index=models.Index(fields=['geoname_id'], name='ciudades_geoname_6520f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='ciudad',
            constraint=models.UniqueConstraint(fields=('nombre', 'pais'), name='unique_ciudad_por_pais'),
        ),
        migrations.AddConstraint(
            model_name='ciudad',
            constraint=models.UniqueConstraint(condition=models.Q(('geoname_id__isnull', False)), fields=('pais', 'geoname_id'), name='unique_ciudad_geoname_por_pais'),
        ),
        migrations.AddIndex(
            model_name='carrera',
            index=models.Index(fields=['facultad', 'nombre'], name='carreras_faculta_d49d6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='carrera',
            constraint=models.UniqueConstraint(fields=('nombre', 'facultad'), name='unique_carrera_por_facultad'),
        ),
        migrations.AddIndex(
            model_name='capitulolibro',
            index=models.Index(fields=['codigo_isbn'], name='capitulos_l_codigo__f70e98_idx'),
        ),
        migrations.AddIndex(
            model_name='autor',
            index=models.Index(fields=['apellidos', 'nombres'], name='autores_apellid_fd4dba_idx'),
        ),
        migrations.AddIndex(
            model_name='autor',
            index=models.Index(fields=['correo'], name='autores_correo_45301d_idx'),
        ),
        migrations.AddIndex(
            model_name='autor',
            index=models.Index(fields=['identificacion'], name='autores_identif_f8f1f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='autor',
            constraint=models.UniqueConstraint(condition=models.Q(('identificacion__isnull', False), models.Q(('identificacion', ''), _negated=True)), fields=('identificacion',), name='unique_autor_identificacion_no_vacia'),
        ),
        migrations.AddConstraint(
            model_name='autor',
            constraint=models.UniqueConstraint(condition=models.Q(('correo__isnull', False), models.Q(('correo', ''), _negated=True)), fields=('correo',), name='unique_autor_correo_no_vacio'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['tipo_articulo'], name='articulos_tipo_ar_0af26a_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['base_datos_indexada'], name='articulos_base_da_ab3ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['factor_impacto', 'cuartil'], name='articulos_factor__df07bd_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['codigo_doi'], name='articulos_codigo__89b8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['codigo_issn'], name='articulos_codigo__131f96_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['nombre_revista'], name='articulos_nombre__7794eb_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='usuarios_rol_936bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['auth_source'], name='usuarios_auth_so_b946ab_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['is_active'], name='usuarios_is_acti_8ee55c_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['is_staff'], name='usuarios_is_staf_ad81a8_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['facultad'], name='usuarios_faculta_b36819_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['carrera'], name='usuarios_carrera_2d47bd_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol', 'is_active'], name='usuarios_rol_b179b6_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['auth_source', 'is_active'], name='usuarios_auth_so_c381b5_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['creado_desde_selector'], name='usuarios_creado__8c4f74_idx'),
        ),
    ]
