# Generated by Django 3.2.25 on 2026-04-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='institucion',
            field=models.CharField(blank=True, help_text='Institución a la que pertenece el autor.', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='autor',
            index=models.Index(fields=['institucion'], name='autores_institu_1226b2_idx'),
        ),
    ]
