# Generated by Django 3.2.25 on 2026-04-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260430_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponencia',
            name='tipo_presentacion_otro',
            field=models.CharField(blank=True, help_text="Valor manual cuando el tipo de presentación seleccionado es 'Otro'.", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='tipo_presentacion',
            field=models.CharField(blank=True, choices=[('magistral', 'Conferencia magistral'), ('oral', 'Conferencia oral'), ('poster', 'Poster'), ('otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='ponencia',
            index=models.Index(fields=['tipo_presentacion'], name='ponencias_tipo_pr_eb5043_idx'),
        ),
    ]
