# Generated by Django 4.2.16 on 2026-06-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20260430_1706'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publicacion',
            name='publicacion_faculta_9df43f_idx',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='usuarios_faculta_b36819_idx',
        ),
        migrations.RemoveField(
            model_name='microsoftmappingrule',
            name='facultad',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='facultad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='facultad',
        ),
    ]
