# Generated by Django 4.2.16 on 2026-07-24 18:14

import core.models.academico
import core.models.banners
import core.models.publicaciones.archivos
import core.models.publicaciones.base
import core.models.usuarios
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_publicacion_publicacion_faculta_9df43f_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacionautor',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', core.models.usuarios.UsuarioManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='pais',
            name='unique_pais_iso2',
        ),
        migrations.RemoveConstraint(
            model_name='pais',
            name='unique_pais_iso3',
        ),
        migrations.AddField(
            model_name='ponencia',
            name='revisor_par_arbitraje',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(max_length=255, upload_to=core.models.banners.banner_upload_to, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='capitulolibro',
            name='link_capitulo',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='libro',
            name='link_libro',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='microsoftmappingrule',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglas_microsoft', to='core.carrera'),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='link_evento',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='tipo_presentacion',
            field=models.CharField(blank=True, choices=[('magistral', 'Conferencia magistral'), ('oral', 'Conferencia oral'), ('poster', 'Póster'), ('otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='tipo_presentacion_otro',
            field=models.CharField(blank=True, help_text="Valor manual cuando el tipo seleccionado es 'Otro'.", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='archivo_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=core.models.academico.proyecto_pdf_upload_path),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='admin_registrador',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('is_staff', True), ('is_superuser', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_registradas_como_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='archivo_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=core.models.publicaciones.base.publicacion_pdf_upload_path),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to='core.areaconocimiento'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to='core.ciudad'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='origen_grado',
            field=models.CharField(blank=True, help_text='Especificar el grado cuando el origen lo requiera.', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to='core.pais'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='subarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to='core.subarea'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='usuario_creador',
            field=models.ForeignKey(limit_choices_to=models.Q(('rol__in', ['autor', 'autor_externo'])), on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicacionarchivo',
            name='archivo',
            field=models.FileField(max_length=255, upload_to=core.models.publicaciones.archivos.publicacion_archivo_upload_path),
        ),
        migrations.AlterField(
            model_name='publicacionautor',
            name='rol_autoria',
            field=models.CharField(choices=[('principal', 'Autor principal'), ('coautor', 'Coautor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='usuarios/avatar/'),
        ),
        migrations.AddConstraint(
            model_name='pais',
            constraint=models.UniqueConstraint(condition=models.Q(('iso2__isnull', False), models.Q(('iso2', ''), _negated=True)), fields=('iso2',), name='unique_pais_iso2'),
        ),
        migrations.AddConstraint(
            model_name='pais',
            constraint=models.UniqueConstraint(condition=models.Q(('iso3__isnull', False), models.Q(('iso3', ''), _negated=True)), fields=('iso3',), name='unique_pais_iso3'),
        ),
        migrations.AddConstraint(
            model_name='publicacionarchivo',
            constraint=models.UniqueConstraint(fields=('publicacion', 'orden'), name='unique_archivo_orden_por_publicacion'),
        ),
        migrations.AddConstraint(
            model_name='publicacionautor',
            constraint=models.UniqueConstraint(condition=models.Q(('rol_autoria', 'principal')), fields=('publicacion',), name='unique_autor_principal_por_publicacion'),
        ),
    ]
