# Generated by Django 4.2.16 on 2026-07-30 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_publicacionautor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cedula', message='La cédula debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
    ]
