# Generated by Django 4.2.16 on 2026-08-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usuario_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='origen_grado',
            field=models.CharField(blank=True, help_text='Especificar el grado o programa cuando el origen sea TIC, o escribir el origen cuando se seleccione Otro.', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='origen_tipo',
            field=models.CharField(choices=[('ninguno', 'Ninguno'), ('tic', 'Trabajo de integración curricular'), ('maestria', 'Tesis de maestría'), ('doctoral', 'Tesis doctoral'), ('otro', 'Otro')], default='ninguno', max_length=20),
        ),
    ]
