# Generated by Django 4.2.16 on 2026-08-06 06:04

import core.models.banners
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_publicacion_origen_grado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to=core.models.banners.banner_upload_to, verbose_name='Imagen'),
        ),
    ]
