# Generated by Django 4.2.16 on 2026-08-06 06:29

import core.models.banners
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(max_length=255, upload_to=core.models.banners.banner_upload_to, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='bannerconfiguracion',
            name='display_mode',
            field=models.CharField(choices=[('banner', 'Solo banner')], default='banner', max_length=16, verbose_name='Modo de visualización'),
        ),
    ]
