# Generated by Django 4.2.16 on 2026-08-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': [models.OrderBy(models.F('publicacion__anio_publicacion'), descending=True), models.OrderBy(models.F('publicacion__mes_publicacion'), descending=True, nulls_last=True), '-id']},
        ),
        migrations.RemoveConstraint(
            model_name='publicacionautor',
            name='unique_autor_principal_por_publicacion',
        ),
        migrations.RemoveIndex(
            model_name='publicacionautor',
            name='publicacion_publica_a826e5_idx',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='publicacionautor',
            name='rol_autoria',
        ),
        migrations.AddField(
            model_name='autor',
            name='google_scholar',
            field=models.URLField(blank=True, help_text='Enlace al perfil de Google Scholar.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='orcid',
            field=models.CharField(blank=True, help_text='Identificador ORCID del autor en formato 0000-0000-0000-0000.', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='registro_senescyt',
            field=models.CharField(blank=True, help_text='Número de registro de investigador SENESCYT.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='scopus_id',
            field=models.CharField(blank=True, help_text='Identificador de autor en Scopus.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='mes_publicacion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='anio_publicacion',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='autor',
            index=models.Index(fields=['registro_senescyt'], name='autores_registr_59f657_idx'),
        ),
        migrations.AddIndex(
            model_name='autor',
            index=models.Index(fields=['scopus_id'], name='autores_scopus__58f526_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['anio_publicacion', 'mes_publicacion'], name='publicacion_anio_pu_e91982_idx'),
        ),
        migrations.AddConstraint(
            model_name='autor',
            constraint=models.UniqueConstraint(condition=models.Q(('orcid__isnull', False), models.Q(('orcid', ''), _negated=True)), fields=('orcid',), name='unique_autor_orcid_no_vacio'),
        ),
    ]
