# Generated by Django 4.2.16 on 2026-08-07 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_articulo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaconocimiento',
            options={'ordering': ['codigo']},
        ),
        migrations.AlterModelOptions(
            name='subarea',
            options={'ordering': ['codigo']},
        ),
        migrations.AddField(
            model_name='areaconocimiento',
            name='codigo',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subarea',
            name='codigo',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subareas', to='core.areaconocimiento'),
        ),
    ]
