# Generated by Django 4.2.16 on 2026-08-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_areaconocimiento_options_alter_subarea_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaconocimiento',
            name='codigo',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='codigo',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
