# Generated by Django 4.2.16 on 2026-08-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_areaconocimiento_codigo_alter_subarea_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='jcr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
