# Generated by Django 4.2.16 on 2026-08-20 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_articulo_jcr"),
    ]

    operations = [
        # ============================================================
        # 1. CREAR SEDE
        # ============================================================
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        unique=True,
                    ),
                ),
                (
                    "ciudad",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                    ),
                ),
            ],
            options={
                "db_table": "sedes",
                "ordering": ["nombre"],
            },
        ),

        # ============================================================
        # 2. CREAR RELACIÓN CARRERA-SEDE
        # ============================================================
        migrations.CreateModel(
            name="CarreraSede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sedes_carrera",
                        to="core.carrera",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carreras_sede",
                        to="core.sede",
                    ),
                ),
            ],
            options={
                "db_table": "carreras_sedes",
                "ordering": [
                    "sede__nombre",
                    "carrera__nombre",
                ],
            },
        ),

        # ============================================================
        # 3. AGREGAR SEDE A LOS MODELOS EXISTENTES
        # ============================================================
        migrations.AddField(
            model_name="proyecto",
            name="sede",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proyectos",
                to="core.sede",
            ),
        ),
        migrations.AddField(
            model_name="publicacion",
            name="sede",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publicaciones",
                to="core.sede",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="sede",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="core.sede",
            ),
        ),

        # ============================================================
        # 4. ÍNDICES DE SEDE
        # ============================================================
        migrations.AddIndex(
            model_name="sede",
            index=models.Index(
                fields=["activa"],
                name="sedes_activa_e1b71f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proyecto",
            index=models.Index(
                fields=["sede"],
                name="proyectos_sede_id_494147_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proyecto",
            index=models.Index(
                fields=[
                    "sede",
                    "anio_inicio",
                ],
                name="proyectos_sede_id_5d97fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publicacion",
            index=models.Index(
                fields=[
                    "sede",
                    "anio_publicacion",
                ],
                name="publicacion_sede_id_cacb5d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(
                fields=["sede"],
                name="usuarios_sede_id_0dc61b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(
                fields=[
                    "sede",
                    "carrera",
                ],
                name="usuarios_sede_id_0f5585_idx",
            ),
        ),

        # ============================================================
        # 5. ÍNDICES Y RESTRICCIÓN CARRERA-SEDE
        # ============================================================
        migrations.AddIndex(
            model_name="carrerasede",
            index=models.Index(
                fields=[
                    "sede",
                    "activa",
                ],
                name="carreras_se_sede_id_ad03e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carrerasede",
            index=models.Index(
                fields=[
                    "carrera",
                    "activa",
                ],
                name="carreras_se_carrera_0bc020_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="carrerasede",
            constraint=models.UniqueConstraint(
                fields=(
                    "sede",
                    "carrera",
                ),
                name="unique_carrera_por_sede",
            ),
        ),
    ]