# Generated by Django 4.2.16 on 2026-09-01 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_comunicacion_global_notificaciones_campania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('publicacion_enviada', 'Publicación enviada'), ('publicacion_observada', 'Publicación observada'), ('publicacion_aprobada', 'Publicación aprobada'), ('publicacion_rechazada', 'Publicación rechazada'), ('nueva_publicacion_revision', 'Nueva publicación para revisar'), ('publicacion_reenviada', 'Publicación corregida y reenviada'), ('solicitud_extension_perfil', 'Solicitud de extensión de perfil'), ('extension_perfil_aprobada', 'Extensión de perfil aprobada'), ('extension_perfil_rechazada', 'Extensión de perfil rechazada'), ('campania_actualizacion', 'Actualización de información requerida'), ('recordatorio_actualizacion', 'Recordatorio de actualización'), ('solicitud_modificacion_publicacion', 'Solicitud de modificación de publicación'), ('modificacion_publicacion_aprobada', 'Modificación de publicación aprobada'), ('modificacion_publicacion_rechazada', 'Modificación de publicación rechazada')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='SolicitudModificacionPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20)),
                ('motivo', models.TextField()),
                ('campos_solicitados', models.JSONField(blank=True, default=list)),
                ('cambios_solicitados', models.JSONField(default=dict)),
                ('datos_anteriores', models.JSONField(blank=True, default=dict)),
                ('publicacion_updated_at_solicitud', models.DateTimeField()),
                ('comentario_resolucion', models.TextField(blank=True, null=True)),
                ('resuelto_at', models.DateTimeField(blank=True, null=True)),
                ('aplicado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_modificacion', to='core.publicacion')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_modificacion_publicaciones_revisadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_modificacion_publicaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitudes_modificacion_publicaciones',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['estado', 'created_at'], name='solmodpub_estado_fecha_idx'), models.Index(fields=['publicacion', 'created_at'], name='solmodpub_pub_fecha_idx'), models.Index(fields=['solicitante', 'created_at'], name='solmodpub_sol_fecha_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='solicitudmodificacionpublicacion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('publicacion', 'solicitante'), name='unique_solmodpub_pendiente_usuario'),
        ),
    ]
