import api from "./axios";
const CAMPAIGNS="admin/actualizaciones", MINE="mis-actualizaciones", AUDIT="admin/auditoria", COMMS="comunicaciones-globales";
const clean=(p={})=>Object.fromEntries(Object.entries(p).filter(([,v])=>v!==""&&v!==null&&v!==undefined));
const data=r=>r?.data??r??null;
export const asResults=p=>Array.isArray(p)?p:(Array.isArray(p?.results)?p.results:[]);
export const apiErrorMessage=(e,f="No se pudo completar la acción.")=>{const d=e?.response?.data;if(typeof d?.detail==="string")return d.detail;if(typeof d==="string")return d;for(const v of Object.values(d||{})){if(typeof v==="string")return v;if(Array.isArray(v)&&v[0])return String(v[0]);}return f};
export const listarCampanias=async(p={})=>data(await api.get(`${CAMPAIGNS}/`,{params:clean(p)}));
export const crearCampania=async(p)=>data(await api.post(`${CAMPAIGNS}/`,p));
export const actualizarCampania=async(id,p)=>data(await api.patch(`${CAMPAIGNS}/${id}/`,p));
export const eliminarCampania=async id=>data(await api.delete(`${CAMPAIGNS}/${id}/`));
export const diagnosticarCampania=async id=>data(await api.get(`${CAMPAIGNS}/${id}/diagnostico/`));
export const activarCampania=async id=>data(await api.post(`${CAMPAIGNS}/${id}/activar/`));
export const finalizarCampania=async id=>data(await api.post(`${CAMPAIGNS}/${id}/finalizar/`));
export const cancelarCampania=async id=>data(await api.post(`${CAMPAIGNS}/${id}/cancelar/`));
export const enviarRecordatorioCampania=async id=>data(await api.post(`${CAMPAIGNS}/${id}/recordatorio/`));
export const recalcularCampania=async id=>data(await api.post(`${CAMPAIGNS}/${id}/recalcular/`));
export const listarParticipantesCampania=async(id,p={})=>data(await api.get(`${CAMPAIGNS}/${id}/participantes/`,{params:clean(p)}));
export const listarMisActualizaciones=async()=>data(await api.get(`${MINE}/`));
export const iniciarMiActualizacion=async id=>data(await api.post(`${MINE}/${id}/iniciar/`));
export const recalcularMiActualizacion=async id=>data(await api.post(`${MINE}/${id}/recalcular/`));
export const sincronizarAvisoMisActualizaciones=async()=>data(await api.post(`${MINE}/estado-aviso/`));
export const listarAuditoria=async(p={})=>data(await api.get(`${AUDIT}/`,{params:clean(p)}));
export const resumenAuditoria=async()=>data(await api.get(`${AUDIT}/resumen/`));
export const exportarAuditoria=(p={})=>api.get(`${AUDIT}/exportar/`,{params:clean(p),responseType:"blob"});
export const listarComunicaciones=async(p={})=>data(await api.get(`${COMMS}/`,{params:clean(p)}));
export const crearComunicacion=async p=>data(await api.post(`${COMMS}/`,p));
export const actualizarComunicacion=async(id,p)=>data(await api.patch(`${COMMS}/${id}/`,p));
export const eliminarComunicacion=async id=>data(await api.delete(`${COMMS}/${id}/`));
